# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Lab/MLP/MLP.srcs/sources_1/bd/zynq_design/ip/zynq_design_MLPHLS_Opt_0_0/zynq_design_MLPHLS_Opt_0_0.xci
# IP: The module: 'zynq_design_MLPHLS_Opt_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Lab/MLP/MLP.gen/sources_1/bd/zynq_design/ip/zynq_design_MLPHLS_Opt_0_0/constraints/MLPHLS_Opt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_MLPHLS_Opt_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Lab/MLP/MLP.srcs/sources_1/bd/zynq_design/ip/zynq_design_MLPHLS_Opt_0_0/zynq_design_MLPHLS_Opt_0_0.xci
# IP: The module: 'zynq_design_MLPHLS_Opt_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Lab/MLP/MLP.gen/sources_1/bd/zynq_design/ip/zynq_design_MLPHLS_Opt_0_0/constraints/MLPHLS_Opt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_MLPHLS_Opt_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
