# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_design/zynq_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_design || ORIG_REF_NAME==zynq_design} -quiet] -quiet

# IP: bd/zynq_design/ip/zynq_design_processing_system7_0_0/zynq_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_design_processing_system7_0_0 || ORIG_REF_NAME==zynq_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_design/ip/zynq_design_axi_gpio_0_0/zynq_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_design_axi_gpio_0_0 || ORIG_REF_NAME==zynq_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zynq_design/ip/zynq_design_xbar_0/zynq_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_design_xbar_0 || ORIG_REF_NAME==zynq_design_xbar_0} -quiet] -quiet

# IP: bd/zynq_design/ip/zynq_design_ps7_0_axi_periph_0/zynq_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq_design/ip/zynq_design_rst_ps7_0_100M_0/zynq_design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==zynq_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zynq_design/ip/zynq_design_axi_fifo_mm_s_0_0/zynq_design_axi_fifo_mm_s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_design_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==zynq_design_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/zynq_design/ip/zynq_design_MLP_RTL_IP_0_0/zynq_design_MLP_RTL_IP_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_design_MLP_RTL_IP_0_0 || ORIG_REF_NAME==zynq_design_MLP_RTL_IP_0_0} -quiet] -quiet

# IP: bd/zynq_design/ip/zynq_design_axi_timer_0_0/zynq_design_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_design_axi_timer_0_0 || ORIG_REF_NAME==zynq_design_axi_timer_0_0} -quiet] -quiet

# IP: bd/zynq_design/ip/zynq_design_axi_fifo_mm_s_1_0/zynq_design_axi_fifo_mm_s_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_design_axi_fifo_mm_s_1_0 || ORIG_REF_NAME==zynq_design_axi_fifo_mm_s_1_0} -quiet] -quiet

# IP: bd/zynq_design/ip/zynq_design_MLPHLS_Opt_0_0/zynq_design_MLPHLS_Opt_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_design_MLPHLS_Opt_0_0 || ORIG_REF_NAME==zynq_design_MLPHLS_Opt_0_0} -quiet] -quiet

# IP: bd/zynq_design/ip/zynq_design_auto_pc_0/zynq_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_design_auto_pc_0 || ORIG_REF_NAME==zynq_design_auto_pc_0} -quiet] -quiet

# XDC: d:/Lab/MLP/MLP.gen/sources_1/bd/zynq_design/zynq_design_ooc.xdc
